[package]
name = "sixtyfps-compiler"
version = "0.0.4"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "SixtyFPS compiler binary"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[[bin]]
name = "sixtyfps_compiler"
path = "main.rs"

[dependencies]
sixtyfps-compilerlib = { version = "=0.0.4", path = "../../sixtyfps_compiler", features = ["display-diagnostics", "cpp", "rust", "qml"]}
structopt = "0.3.11"
spin_on = "0.1"
